### ISSUE TITLE
Distribution of occupancy across species

### ISSUE THREAD

**Issue by drnickisaac** [ibartomeus/SimPoly#2]
@ibartomeus asked us to consider alternatives to this code on line 21 of `sp_pool.r`:
`distrib <- runif(pool, rarest, commonest)`

This will tend to produce more widespread species than typcial communities. One way to change this would be to replace with a beta distribution. The architecture would need to change a bit, but the distribution is quite flexible and moderately easy to use.

**Comment by ibartomeus** [comment]
Noted. I never used it but I see it needs a couple of params: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Beta.html ANy tips on how to relate those two params to max and minimum occupancy (or mean occupancy, or whatever) are welcome.

**Comment by drnickisaac** [comment]
You'd need to add the two beta parameters as arguments. 
I would suggest to include the min and max occupancy as optional additional parameters.
Try
`distrib <- rbeta(pool, 1, 3)`
`distrib <- sapply(distrib, function(x) min(x, rarest))`
`distrib <- sapply(distrib, function(x) max(x, commonest))`

**Comment by ibartomeus** [comment]
Fixed! Thanks Nick.
