### ISSUE TITLE
combined comments

### ISSUE THREAD

**Issue by oliverschweiger** [ibartomeus/SimPoly#3]
Sp_pool
L21 runif seems suboptimal. Agree to let it be informed by data. If possible identify a relationship between the shape of the distribution and biogeographic factors (e.g. climate). I can give it a try, e.g. with eBMS data.

Define_sites_years
L3  rnorm: Agree to let it be informed by data, but assuming a normal distribution seem quite plausible, but why not using a Poisson distribution? Rich_mean and richness_sd (or lambda for rpois) might be more important to be informed by data (and by biogeography).
L39 assumption of no immigration or emigration: but this will not allow for simulating changes in species richness, or will this be addressed by the species trends?

Sp_responses
L27 Why hard-coding the days of the year?
L32 Rather fair, but bimodal might be more realistic. Or just use a more left-skewed distribution?
L33 Should be OK
L38 Might be nice to have the option to include different distributions. Max (or average) abundances could also be informed by data across biogeographic gradients.
L42 Agreed, we may go for a normal distribution (or some level of skewness) with the option to specify mean (or median) and sd. Might also be linked to the level of occupancy and/or abundance. Rare species might be expected to respond stronger (to the good or bad) than common ones. But perhaps also keep the option of random variation.
L48 Yes, function of h, but with a certain random component?

True_abundance
L31 Don’t know. But too few years might be problem?
L46 Is it also possible to gain species (e.g. starting with zero abundance in the first years)?

Obs_abundance
L22 Why hard-coding fraction_observed?
L50 adding noise might be good.

**Comment by anamontcast** [comment]
From my side, just a couple of comments, as most of my doubts are already discussed in the other issues: 
sp_pool
Following Oli's comment about informing with data the shape of the distribution, we (JRC) can also look for that in the compiled datasets.

sp_responses
The possibility of an abundance-dependent assignation of phenology, instead of the current random assignation.

**Comment by ibartomeus** [comment]
Fixed or left comments on the code for future implementations.
